### ISSUE TITLE
Windows support please.

### ISSUE THREAD

**Issue by expnkx** [urnathan/libcody#15]
https://github.com/expnkx/fast_io/blob/master/include/fast_io_network/win32_socket.h

#include <sys/socket.h>

**Comment by expnkx** [comment]
I think do not understand Win32 APIs and it is very hard to get your code work on Windows it looks like. Your code only works on Unix-like OS which means we will not get module support for GCC on Windows for near 5 years.

BTW __windows__ macro does not exist on MinGW-w64. It should be _WIN32.
 
1. POSIX file descriptors on Windows does not provide networking service, either HANDLE. The handle gets from win32 API is not the HANDLE from CreateFileW, unlike UNIX systems.
2. FILE* is extremely slow. Your library will definitely be a performance bottle because of FILE*.

For example, this API provided for your GCC branch. Unfortunately, windows do not provide networking for the file descriptors. :

  int Read (int fd) noexcept;

public:
  /// Write to an end point from a write buffer, as with write(2).  As
  /// with Read, this will not usually block.
  /// @param fd file descriptor to write to.  This may be a regular
  /// file, pipe or socket.
  /// @result on error returns errno.
  /// At end of message returns 0.  If there is more to write
  /// returns EAGAIN (or possibly EINTR).
  int Write (int fd) noexcept;


I think if you can just get your work around the pipe, that would be better than sockets since all operating system provides pipe.

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/pipe?view=vs-2019

**Comment by urnathan** [comment]
Yes, windows support would be good. Sadly, I'm not the right person to address that.  The last time I did anything windowy it was mingw, over a decade ago.  I don't have any window development systems.

The library needs to be able to support sockets, not just pipes, btw.

anyway, as they say, 'patches welcome'

**Comment by expnkx** [comment]
https://bitbucket.org/ejsvifq_mabmip/mingw-gcc/src/master/

Here is the compiler I just build today.
![image](https://user-images.githubusercontent.com/57303909/94806864-add3b580-03bc-11eb-8d43-ba8df5aff6c5.png)

This is my msys2 package
https://bitbucket.org/ejsvifq_mabmip/mingw-gcc-mcfgthread-pacman/src/master/

**Comment by expnkx** [comment]
For socket, you can borrow code 

Here is a one to one translation of win32 socket API to POSIX API
https://github.com/expnkx/fast_io/blob/master/include/fast_io_network/win32_socket.h

https://github.com/expnkx/fast_io/blob/master/include/fast_io_network/posix_socket.h

**Comment by expnkx** [comment]
I can help you port the code to windows, but you have to remove all code related to the file descriptor of sockets in your GCC branch.

**Comment by expnkx** [comment]
I think you should also provide stuff that does not require any cross-process build stuff since it will further harm C++ freestanding and bootstrapping for the barebone operating system.

**Comment by expnkx** [comment]
@urnathan Hi urnathan. I have another approach. We can use a separate process or thread for emulating POSIX networking APIs to make fd work on Windows.

**Comment by wilx** [comment]
I took a look at the code and it seems it is a bit Linux centric. There are things that I think might fail on less mainstream platforms. I offer [`socket-unix.cxx`](https://github.com/log4cplus/log4cplus/blob/master/src/socket-unix.cxx) and [`socket-win32.cxx`](https://github.com/log4cplus/log4cplus/blob/master/src/socket-win32.cxx) for inspiration on what I had to deal with to make it portable between NIX platforms and Windows under facade of one API. 

Also, I see, e.g., `connect()` does not deal with `EINTR`. 

Is forking a concern? Maybe some of the handles should be close-on-exec?

I can't find any `accept()` call in the code but that has issues with portability as well, due to different signature in different OSes.

I am not saying the way log4cplus does it is the best way but it certainly works for the limited use cases it has and it is portable between many systems while still being a very thin wrapper like you seem to be trying to do. HTH.

**Comment by expnkx** [comment]
> I took a look at the code and it seems it is a bit Linux centric. There are things that I think might fail on less mainstream platforms. I offer [`socket-unix.cxx`](https://github.com/log4cplus/log4cplus/blob/master/src/socket-unix.cxx) and [`socket-win32.cxx`](https://github.com/log4cplus/log4cplus/blob/master/src/socket-win32.cxx) for inspiration on what I had to deal with to make it portable between NIX platforms and Windows under facade of one API.
> 
> Also, I see, e.g., `connect()` does not deal with `EINTR`.
> 
> Is forking a concern? Maybe some of the handles should be close-on-exec?
> 
> I can't find any `accept()` call in the code but that has issues with portability as well, due to different signature in different OSes.
> 
> I am not saying the way log4cplus does it is the best way but it certainly works for the limited use cases it has and it is portable between many systems while still being a very thin wrapper like you seem to be trying to do. HTH.

1. that was my silliness. They have already supported concepts. I should close this issue.
2. Just supporting networking isn't very hard. The issue is that libcody requires the POSIX file descriptor system. fd on windows does not support socket, neither WIN32 or NT would support it.
3. I disagree with dealing EINTR errno.
4. These logging libraries are problems since they have format strings. format strings = vulns.
