### ISSUE TITLE
fatal.cc:42:25: error: ‘SRCDIR’ was not declared in this scope

### ISSUE THREAD

**Issue by Johnny-Martin** [urnathan/libcody#2]
This error ocured when I make this project: 
OS: Ubuntu 18.04 (WSL2)

Parallelizing 4 ways
make -r -j --jobserver-fds=3,4
make[1]: Entering directory '/mnt/d/Code/GCC/libcody'
rm -f .gdbinit ; ln -s gdbinit .gdbinit
g++ -g -O2 -fno-enforce-eh-specs -fno-stack-protector -fno-threadsafe-statics -fno-exceptions -fno-rtti -fdebug-prefix-map=./= -W -Wall -Woverloaded-virtual -Wshadow -Wno-invalid-offsetof -Wno-unused-variable -Wno-missing-field-initializers -fmessage-length=133 -fdiagnostics-color=always -fno-diagnostics-show-option -include config.h -MMD -MP -MF buffer.d -I . -c -o buffer.o buffer.cc
g++ -g -O2 -fno-enforce-eh-specs -fno-stack-protector -fno-threadsafe-statics -fno-exceptions -fno-rtti -fdebug-prefix-map=./= -W -Wall -Woverloaded-virtual -Wshadow -Wno-invalid-offsetof -Wno-unused-variable -Wno-missing-field-initializers -fmessage-length=133 -fdiagnostics-color=always -fno-diagnostics-show-option -include config.h -MMD -MP -MF client.d -I . -c -o client.o client.cc
g++ -g -O2 -fno-enforce-eh-specs -fno-stack-protector -fno-threadsafe-statics -fno-exceptions -fno-rtti -fdebug-prefix-map=./= -W -Wall -Woverloaded-virtual -Wshadow -Wno-invalid-offsetof -Wno-unused-variable -Wno-missing-field-initializers -fmessage-length=133 -fdiagnostics-color=always -fno-diagnostics-show-option -include config.h -MMD -MP -MF netclient.d -I . -c -o netclient.o netclient.cc
g++ -g -O2 -fno-enforce-eh-specs -fno-stack-protector -fno-threadsafe-statics -fno-exceptions -fno-rtti -fdebug-prefix-map=./= -W -Wall -Woverloaded-virtual -Wshadow -Wno-invalid-offsetof -Wno-unused-variable -Wno-missing-field-initializers -fmessage-length=133 -fdiagnostics-color=always -fno-diagnostics-show-option -include config.h -MMD -MP -MF netserver.d -I . -c -o netserver.o netserver.cc
g++ -g -O2 -fno-enforce-eh-specs -fno-stack-protector -fno-threadsafe-statics -fno-exceptions -fno-rtti -fdebug-prefix-map=./= -W -Wall -Woverloaded-virtual -Wshadow -Wno-invalid-offsetof -Wno-unused-variable -Wno-missing-field-initializers -fmessage-length=133 -fdiagnostics-color=always -fno-diagnostics-show-option -include config.h -MMD -MP -MF packet.d -I . -c -o packet.o packet.cc
g++ -g -O2 -fno-enforce-eh-specs -fno-stack-protector -fno-threadsafe-statics -fno-exceptions -fno-rtti -fdebug-prefix-map=./= -W -Wall -Woverloaded-virtual -Wshadow -Wno-invalid-offsetof -Wno-unused-variable -Wno-missing-field-initializers -fmessage-length=133 -fdiagnostics-color=always -fno-diagnostics-show-option -include config.h -MMD -MP -MF resolver.d -I . -c -o resolver.o resolver.cc
g++ -g -O2 -fno-enforce-eh-specs -fno-stack-protector -fno-threadsafe-statics -fno-exceptions -fno-rtti -fdebug-prefix-map=./= -W -Wall -Woverloaded-virtual -Wshadow -Wno-invalid-offsetof -Wno-unused-variable -Wno-missing-field-initializers -fmessage-length=133 -fdiagnostics-color=always -fno-diagnostics-show-option -include config.h -MMD -MP -MF server.d -I . -c -o server.o server.cc
g++ -g -O2 -fno-enforce-eh-specs -fno-stack-protector -fno-threadsafe-statics -fno-exceptions -fno-rtti -fdebug-prefix-map=./= -W -Wall -Woverloaded-virtual -Wshadow -Wno-invalid-offsetof -Wno-unused-variable -Wno-missing-field-initializers -fmessage-length=133 -fdiagnostics-color=always -fno-diagnostics-show-option -include config.h -MMD -MP -MF fatal.d -I . -c -o fatal.o fatal.cc
fatal.cc: In function ‘void Cody::HCF(const char*, Cody::Location)’:
fatal.cc:42:25: error: ‘SRCDIR’ was not declared in this scope
       char const *src = SRCDIR;
                         ^~~~~~
fatal.cc:42:25: note: suggested alternative: ‘EISDIR’
       char const *src = SRCDIR;
                         ^~~~~~
                         EISDIR
fatal.cc: In function ‘void Cody::BuildNote(FILE*)’:
fatal.cc:64:7: error: ‘REVISION’ was not declared in this scope
   if (REVISION[0])
       ^~~~~~~~
fatal.cc:64:7: note: suggested alternative: ‘EISCONN’
   if (REVISION[0])
       ^~~~~~~~
       EISCONN
Makefile:87: recipe for target 'fatal.o' failed
make[1]: *** [fatal.o] Error 1
make[1]: Leaving directory '/mnt/d/Code/GCC/libcody'
Makefile:27: recipe for target 'recurse' failed
make: *** [recurse] Error 2

**Comment by jjravi** [comment]
Don't try to compile in the root source directory. Follow these steps:

`mkdir libcody`
`cd libcody`
`mkdir obj src`
`git clone https://github.com/urnathan/libcody.git src`
`cd obj`
`../src/configure`
`make -j`

**Comment by Johnny-Martin** [comment]
@jjravi  Thanks！ It works now :)

**Comment by urnathan** [comment]
Thanks jjravi, I'll see about adding smarts to avoid the failure mode the reporter encountered.

**Comment by urnathan** [comment]
2259a5e pushed.  shouts at you if you try and configure in the src dir
